module.exports = {
  reference: {
    '网站概览': [
      'intro/intro',
      // 'intro/why-rust',
      // 'intro/why-webassembly',
      // 'intro/how-it-works',
      // 'intro/ink-vs-solidity',
    ],
    '基础知识': [
      'getting-started/setup',
      'getting-started/creating',
      'getting-started/compiling',
      'getting-started/running',
      'getting-started/deploying',
      'getting-started/calling',
      'getting-started/troubleshooting',
    ],
    '系统运维': [
      'basics/contract-template',
      'basics/storing-values',
      'basics/reading-values',
      'basics/mutating-values',
      'basics/events',
      'basics/trait-definitions',
      'basics/cross-contract-calling',
      'basics/testing',
      'basics/env-functions',
    ],
    'Bitcoin': [
      'macros-attributes/overview',
      'macros-attributes/contract',
      'macros-attributes/anonymous',
      'macros-attributes/constructor',
      'macros-attributes/event',
      'macros-attributes/implementation',
      'macros-attributes/message',
      'macros-attributes/namespace',
      'macros-attributes/payable',
      'macros-attributes/selector',
      'macros-attributes/storage',
      'macros-attributes/topic',
      'macros-attributes/chain-extension',
    ],
    'Ethereum': [
      'datastructures/overview',
      'datastructures/hashmap',
      'datastructures/spread-packed',
      'datastructures/opting-out',
      'datastructures/dynamic-allocation',
      'datastructures/custom',
    ],
    'Polkadot': [
      'examples/overview',
    ],
    '编程语言': [
      'cargo-contract/overview',
    ],
    'WebAssembly': [
      'canvas/overview',
    ],
    'FAQ': [
      'faq/faq',
    ],
  },
};
